<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ThighPhysicsController</AssemblyName>
    <TargetFramework>net20</TargetFramework>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <GameRoot Condition="'$(KOIKATU_BUILD_GAME_ROOT)' != ''">$(KOIKATU_BUILD_GAME_ROOT)</GameRoot>
    <GameRoot Condition="'$(GameRoot)' == ''">Z:\Koikatu</GameRoot>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(GameRoot)\BepInEx\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(GameRoot)\BepInEx\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameRoot)\Koikatu_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameRoot)\Koikatu_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="KKAPI">
      <HintPath>$(GameRoot)\BepInEx\plugins\KKAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ExtensibleSaveFormat">
      <HintPath>$(GameRoot)\BepInEx\plugins\KK_BepisPlugins\ExtensibleSaveFormat.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Xml" />
  </ItemGroup>
</Project>
